default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') { 'postgres' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>
  username: <%= ENV.fetch('POSTGRES_USER') { 'postgres' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: opentelemetry_rails_dev
    <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>
  queue:
    <<: *default
    database: opentelemetry_rails_dev_queue
    <% if RUBY_PLATFORM =~ /darwin/ %>gssencmode: disable<% end %>

test:
  <<: *default
  database: opentelemetry_rails_test

production:
  primary: &primary_production
    <<: *default
    database: opentelemetry_rails_production
  queue:
    <<: *primary_production
    database: opentelemetry_rails_production_queue
