{
 "title": "Rails HTTP Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "http_route",
    "query": {
     "query": "label_values(traces_span_metrics_calls_total,http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{http_route=~\"$http_route\"}[2m]))"
    }
   ]
  },
  {
   "title": "Avg. latency",
   "type": "stat",
   "description": "no healthchecks and OPTIONS",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traces_span_metrics_duration_milliseconds_sum{http_route=~\"$http_route\"}[2m])) / sum(rate(traces_span_metrics_duration_milliseconds_count{http_route=~\"$http_route\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(traces_span_metrics_duration_milliseconds_bucket{http_route=~\"$http_route\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_span_metrics_calls_total{http_route=~\"$http_route\",http_status_code=~\"5.*\"}[$__range]))\nor vector(0)"
    }
   ]
  },
  {
   "title": "Breakdown by endpoints",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(traces_span_metrics_duration_milliseconds_bucket{http_route!=\"\"}[2m])) by (le,http_route,http_method))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_span_metrics_duration_milliseconds_bucket{http_route!=\"\"}[2m])) by (le,http_route,http_method))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(traces_span_metrics_duration_milliseconds_bucket{http_route!=\"\"}[2m])) by (le,http_route,http_method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(http_method,http_route) (rate(traces_span_metrics_duration_milliseconds_sum{http_route=~\"$http_route\"}[2m])) / sum by(http_route,http_method) (rate(traces_span_metrics_duration_milliseconds_count{http_route=~\"$http_route\"}[2m])) > 0",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Responses by code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_status_code) (rate(traces_span_metrics_duration_milliseconds_count{http_route=~\"$http_route\"}[2m])) > 0",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Throughput by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(http_method,http_route) (rate(traces_span_metrics_duration_milliseconds_count{http_route=~\"$http_route\"}[2m])) > 0.001",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  }
 ]
}