source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgres as the database for Active Record
gem "pg"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# logging
gem "amazing_print"
gem "rails_semantic_logger"

# tracing
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-instrumentation-net_http"
gem "opentelemetry-instrumentation-pg"
gem "opentelemetry-instrumentation-rack"
gem "opentelemetry-instrumentation-rails"

# metrics
gem "statsd-rack-instrument"

group :development, :test do
  gem "pry"
  gem "rspec-rails"
  gem "guard"
  gem "guard-rspec", require: false
  gem "webmock"
  gem "dotenv"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
end

gem "solid_queue", "~> 1.1"

gem "kamal", "~> 2.5", require: false
