global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ prometheus:9090 ]

  - job_name: tempo
    static_configs:
      - targets: [ 'tempo:3200' ]

remote_write:
  - url: http://prometheus:9090/api/v1/write
