global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spanmetrics'
    static_configs:
      - targets: ['otelcol:8889']

  - job_name: prometheus
    static_configs:
      - targets: [ prometheus:9090 ]

  - job_name: tempo
    static_configs:
      - targets: [ 'tempo:3200' ]
