{
 "title": "Rack API Performance",
 "time": { "from": "2024-01-21T20:47:13.983Z", "to": "2024-01-21T20:53:42.842Z" },
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(rack_server_request_duration_seconds_count,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Avg. throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(rack_server_request_duration_seconds_count{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Avg. latency",
   "type": "stat",
   "description": "no healthchecks and OPTIONS",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rack_server_request_duration_seconds_sum{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval]) ) / sum(rate(rack_server_request_duration_seconds_count{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (rate(rack_server_request_duration_seconds_bucket{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(rack_server_request_duration_seconds_count{path!=\"/health\",path=~\"$path\",code=~\"5.*\"}[$__range]))\nor vector(0)"
    }
   ]
  },
  {
   "title": "Breakdown by endpoints",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(rack_server_request_duration_seconds_bucket[5m])) by (le,method,path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rack_server_request_duration_seconds_bucket[5m])) by (le,method,path))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rack_server_request_duration_seconds_bucket[5m])) by (le,method,path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(rack_server_request_duration_seconds_sum{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval])) / sum by(path,method) (rate(rack_server_request_duration_seconds_count{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval])) > 0",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Responses by code",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(rack_server_request_duration_seconds_count{path=~\"$path\"}[$__rate_interval])) > 0",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Throughput by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path,method) (rate(rack_server_request_duration_seconds_count{path!=\"/health\",method!=\"options\",path=~\"$path\"}[$__rate_interval])) > 0.001",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  }
 ]
}